package;

/**
 * ...
 * @author ninjamuffin99
 */
class ChatLogs 
{

	public static var chat:Array<Dynamic> = 
	[
		[
			"!uptime",
			"monkaW",
			"monkaS",
			"omg",
			"!instagram",
			"lol",
			"jebaited",
			"stream gettin lit",
			'thx',
			'yo stream kinda laggy',
			"Why can't womeen just be themselves all the time!? Seriously, this is what guys want a woman who knows how to have fun and not give a shit!",
			"Someone get this man laid^",
			"OOOOOOOOOOHHHHH",
			"this outfit cute",
			"dafuq",
			"haHAAA",
			"YASSSSS",
			"YES",
			"OOOOOOOOOOOOOOOOOOOOOO",
			"hahahahahaha",
			"jesus...",
			"lmaoooooo",
			"heyyyy gurlllll",
			"hmmm",
			"i love your streams",
			"pepeLaugh",
			"OMEGALUL",
			"nah you an angel",
			"LULW",
			"too cute",
			"monkaHmmm",
			"ASMR",
			"monksS",
			"Tik tok",
			"i miss you",
			"saved pog"
		],
		[
			"what bra size do you wear?",
			"check your dms",
			"what yo toes look like",
			"dm bb",
			"werk it gurl",
			"can i have mod?",
			"show toes",
			"hey cutie",
			"lets have sex",
			"boobs",
			"that booty fat",
			"thiccc",
			"thicc",
			"thicj",
			"mommy"
		],
		[
			"POGGRS",
			"LIVE FINNALLY",
			"LIVE POGGERS",
			"pepeJAMJAM pepeJAMJAM pepeJAMJAM\npepeJAMJAM pepeJAMJAM\npepeJAMJAM pepeJAMJAM\npepeJAMJAM pepeJAMJAM",
			"hello",
			"hey",
			"fortnite",
			"pepeJAM",
			"hello beautiful",
			"HI",
			"yeeeee",
			"what up",
			"Yeet",
			"pepeD",
			"lol",
			"Heyyyy gurrlllll",
			"Hey cutie",
			"POGGY POGGERS POGGY POGGERS \nPOGGERS POGGERS\nPOGGERS POGGERS",
			"hmmm",
			"GANG",
			"KAPP",
			"yoooooooooooooo"
		]
		
	];
	
	public static var users:Array<String> = 
	[
		"Flashey",
		"YoR0b",
		"wowitsadlai",
		"theerockaflocka",
		"flycus",
		"BoltznNutz",
		"thenintenboy",
		"VauIt-Tec",
		"SolidusSnake",
		"johnwick35",
		"ctizzle10",
		"TommyGunz718",
		"supersheppo182",
		"woejobb",
		"JAUNT18_",
		"DroopyRed",
		"patriccc14444",
		"klepticgamer",
		"itzchronicgaming",
		"thebadmooddude",
		"gracedanyelle",
		"joynny_mack98",
		"ttv_moose_eeg",
		"jackkooba",
		"ernburn420",
		"bemore509",
		"xBonGMan",
		"fondcrayfish712",
		"jGibson05",
		"NickPDF",
		"dingdongjohns0n",
		"WetDookie",
		"PsychoBKilla",
		"LEGENDERY9",
		"Lejitt",
		"Kalvinpatel",
		"zikonation",
		"OG_Buff",
		"killerfish",
		"hka99",
		"raine881",
		"Yuvall",
		"DealerMDL",
		"OG_Buff3R",
		"Haawkan",
		"killatdusk",
		"jjcoll110",
		"respect_nothing",
		"jimmychongas123",
		"Jadson7",
		"punkey",
		"pauts",
		"Xelxelxelxel",
		"globalethan",
		"OVERKILLX7",
		"yungbruh_",
		"Xbakingsoda",
		"Sassy_Snipez",
		"greypand",
		"Mircidiot",
		"Kenyy",
		"shaurs",
		"LackOfAtten",
		"grande_peru",
		"greypand",
		"YuunoFPS",
		"Zurien4head",
		"some_king_of_forsenCD",
		"appleorbanana",
		"deangalloway",
		"Arkane43",
		"mouth52",
		"Necroguptor",
		"graphiteveins",
		"Jonny_Frostbite",
		"w1nd1r",
		"Keymotes",
		"LumiGG",
		"Amber_ly",
		"rickest_rick_there_is",
		"Isaac226",
		"Crodex",
		"IAmTheOneNeo2",
		"ganjamon17",
		"Sw1zzy",
		"smokingfunking",
		"mariopaintgirl",
		"empereur_js",
		"wallstreetkid",
		"Tatamer123",
		"Reilock",
		"aatrez",
		"Tem_pestK",
		"inFusionxD",
		"ProkL",
		"Davidbleep",
		"SirFeedAlotPT",
		"mamrat",
		"Riptwo",
		"goweller",
		"FallenUtopia_",
		"REV_jIM_jONES",
		"Dsingis",
		"Tem_pestK",
		"CycloneGU",
		"gustii42",
		"Spaceforce",
		"Gracieluwho",
		"kuspkey",
		"capconchi",
		"avokaphs",
		"matrix311xd",
		"finny69",
		"danya1036",
		"basculetheteller",
		"NadeTag",
		"papabeard",
		"vaehx",
		"3ash",
		"LYNX_Andy",
		"yukichocomilk",
		"justinbliss",
		"Zen_yoggurt",
		"bingbingbong",
		"chainsawgaming",
		"DubiousDelerium"
	];
}